-- this file is generated by program!
-- don't change it manaully.
-- source file: example_building.xls
-- created at: Fri Sep 23 10:43:00 2016


local output_building = {}


output_building[1] = {
	id = 1,
	name = "house",
	use_money = 1000,
	use_food = 123,
	is_init = "false",
	defense = 100,
	desc = "好",
	cost = "{1,1,1}",
}

output_building[2] = {
	id = 2,
	name = "church",
	use_money = 5005,
	use_food = 56,
	is_init = "false",
	defense = 513,
	desc = "不好",
	cost = "{1,1,1}",
}

output_building[3] = {
	id = 3,
	name = "school",
	use_money = 334,
	use_food = 153,
	is_init = "false",
	defense = 100,
	desc = "贵",
	cost = "{1,1,100}",
}

output_building[4] = {
	id = 4,
	name = "tomb",
	use_money = 11,
	use_food = 153,
	is_init = "false",
	defense = 221,
	desc = "傻瓜才买",
	cost = "{1,100,1}",
}

output_building.all_type= {}
local all_type = output_building.all_type
all_type[1] = 1s
all_type[2] = 2s
all_type[3] = 3s
all_type[4] = 4s



for i=1, #(output_building.all_type) do
    local item = output_building.all_type[i]
    for j=1, #item do
        item[j].__index = item[j]
        if j < #item then
            setmetatable(item[j+1], item[j])
        end
    end
end


return output_building

